### ISSUE TITLE
[sphgen] Error in use chimera to generate receptor.sph file

### ISSUE THREAD

**Issue by Ding-qh** [PaulaJLR/BLinDPyPr#1]
Use one part of your code to get receptor.sph, which is the following part:
chimera_in='''from chimera import runCommand, openModels, MSMSModel
runCommand("surf")
surf = openModels.list(modelTypes=[MSMSModel])[0]
surf = openModels.list(modelTypes=[MSMSModel])[0]
writeDMS(surf, "receptor.ms")'''
chimeradms = open('ms.py', 'w+'); chimeradms.write(chimera_in); chimeradms.close()
os.system('chimera --nogui receptor_tmp.mol2 ms.py')
sphgen_in='''receptor.ms
R
X
0.0
4.0
1.4
spheres.sph'''
sphgen = open('INSPH', 'w+'); sphgen.write(sphgen_in); sphgen.close()
os.system("sphgen")
Get the following error:
![image](https://user-images.githubusercontent.com/89857420/233928105-1acc8725-c647-415c-9d2e-c99ad95f5460.png)
I guess it is caused by * appearing in the temp3.atc file. What is the solution.
temp3.atc file content as 
![image](https://user-images.githubusercontent.com/89857420/233928136-ea0dafd7-c1c7-438a-b221-458ec735a950.png)

**Comment by PaulaJLR** [comment]
Hi, this usually happens when the target protein has a surface that is challenging for chimera to calculate (described [here](https://www.rbvi.ucsf.edu/chimera/docs/UsersGuide/surfprobs.html)), and so the generated surface can't be properly read by sphgen. This can sometimes be avoided by not calculating for any small and buried internal cavities the protein might have, so  I've updated the command to use `allComponents false`. The next version of blindpypr will support [sphgen_cpp](https://dock.compbio.ucsf.edu/Contributed_Code/sphgen_cpp.htm), which tolerates better these surface calculation errors. Hope this helps

**Comment by Ding-qh** [comment]
> 

Thank you for your help. I'll try
